name: 'Bump submodule'
description: 'Bump specified third-party submodule for integration testing'

inputs:
  submodule:
    description: Name of submodule to bump.
    required: true
    type: string
  revision:
    description: Git revision from submodule repository
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: Bump ${{ inputs.submodule }} submodule
      shell: bash
      run: |
        git submodule update --init third_party/${{ inputs.submodule }}
        pushd third_party/${{ inputs.submodule }}
        git fetch origin
        git checkout ${{ inputs.revision }}
        popd
        # XXX: export the following environment variables to
        # suppress git config warning. The commit is required to
        # avoid resetting dirty changes in the submodule.
        export GIT_COMMITTER_NAME="Integration tester"
        export GIT_COMMITTER_EMAIL="noreply@tarantool.org"
        export GIT_AUTHOR_NAME="Integration tester"
        export GIT_AUTHOR_EMAIL="noreply@tarantool.org"
        # XXX: --allow-empty is required to rerun flaky tests
        # for HEAD when it is already bumped
        # in tarantool/tarantool repo to the same revision.
        # Otherwise the command below fails with "nothing to
        # commit" reason.
        git commit --allow-empty -m ${{ inputs.submodule }}": integration testing bump" \
          third_party/${{ inputs.submodule }}
